# Generated by Django 4.1.6 on 2023-02-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=60)),
                ('author_name', models.CharField(max_length=60)),
                ('price', models.FloatField(default=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='abc.jpg', upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.category')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
