# Generated by Django 4.1.6 on 2023-03-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=5)),
                ('expiry', models.CharField(max_length=12)),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'Payment_Card',
            },
        ),
    ]
