# Generated by Django 4.1.6 on 2023-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0004_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
