# Generated by Django 4.1.6 on 2023-04-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0006_alter_userinfo_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'ContactInfo',
            },
        ),
    ]
