# Generated by Django 4.1.6 on 2023-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0007_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default=1, max_length=254),
        ),
    ]
