# Generated by Django 4.1.6 on 2023-07-17 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0008_alter_contactinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 21, 19, 15, 24, 160705)),
        ),
    ]
